"""Three-level cost-aware CAD behavior benchmark."""

from .allocation import Allocation, optimize_allocation
from .schema import AuditRecord, EditState, GenerationRecord, Template
from .variance import VarianceComponents, estimate_variance_components
from .audit import MASTER_SEED, freeze_sixteen_states, sample_frozen_states, validate_parameters
from .judge import CheckResult, JudgeDecision, judge_geometry
from .protocol import (
    aggregate_components,
    cluster_bootstrap,
    fixed_depth,
    holm_adjust,
    inverse_probability_confusion,
    leave_one_out_components,
    paired_difference,
    shrink_components,
    stratified_state_indices,
)
from .strategies import (
    AllocationRule,
    CostModel,
    CostSummary,
    StratifiedAllocation,
    StratifiedVarianceComponents,
    average_cost_model,
    calibration_break_even_rounds,
    estimate_stratified_variance_components,
    fixed_depth_allocation,
    holm_adjusted_pvalues,
    holm_rejections,
    leave_one_system_out_allocations,
    leave_one_system_out_rule,
    measured_cost_model,
    optimize_stratified_allocation,
    paired_allocation,
    paired_cost_model,
    paired_observations,
    paired_risk_difference,
    paired_variance_components,
    pooled_allocations,
    select_pilot_shrinkage_weight,
    select_pooled_rule,
    small_pilot_allocation,
    stratified_risk,
    stratified_state_sample,
    stratified_variance,
    summarize_costs,
    trimmed_mean,
)
from .replay import (
    DEFAULT_REPLAY_SEED,
    FiniteAuditPool,
    FinitePoolShape,
    ReplayDraw,
    ReplayResult,
    finite_pool_replay,
)

__all__ = [
    "Allocation",
    "AuditRecord",
    "EditState",
    "GenerationRecord",
    "Template",
    "VarianceComponents",
    "estimate_variance_components",
    "MASTER_SEED",
    "freeze_sixteen_states",
    "sample_frozen_states",
    "validate_parameters",
    "CheckResult",
    "JudgeDecision",
    "judge_geometry",
    "optimize_allocation",
    "aggregate_components",
    "cluster_bootstrap",
    "fixed_depth",
    "holm_adjust",
    "inverse_probability_confusion",
    "leave_one_out_components",
    "paired_difference",
    "shrink_components",
    "stratified_state_indices",
    "AllocationRule",
    "CostModel",
    "CostSummary",
    "StratifiedAllocation",
    "StratifiedVarianceComponents",
    "average_cost_model",
    "calibration_break_even_rounds",
    "estimate_stratified_variance_components",
    "fixed_depth_allocation",
    "holm_adjusted_pvalues",
    "holm_rejections",
    "leave_one_system_out_allocations",
    "leave_one_system_out_rule",
    "measured_cost_model",
    "optimize_stratified_allocation",
    "paired_allocation",
    "paired_cost_model",
    "paired_observations",
    "paired_risk_difference",
    "paired_variance_components",
    "pooled_allocations",
    "select_pilot_shrinkage_weight",
    "select_pooled_rule",
    "small_pilot_allocation",
    "stratified_risk",
    "stratified_state_sample",
    "stratified_variance",
    "summarize_costs",
    "trimmed_mean",
    "DEFAULT_REPLAY_SEED",
    "FiniteAuditPool",
    "FinitePoolShape",
    "ReplayDraw",
    "ReplayResult",
    "finite_pool_replay",
]
